Bootcamp/andrewdorscheid-c/Module-3/20_Week4_Review/student-lecture/World/World/Models/CitySearchVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using WorldLib.Models;

namespace World.Models
{
    public class CitySearchVM
    {
        // Display Data Annotation to set a label for these fields
        [Display(Name = "Country Code", Prompt = "3-character ISO code")]
        public string CountryCode { get; set; }

        [Display(Prompt = "e.g., Ohio")]
        public string District { get; set; }
        public IList<City> Cities { get; set; }

        // A place to store a list of countries to the view-model
        public SelectList CountryList { get; set; }
    }
}

Bootcamp/andrewdorscheid-c/Module-3/20_Week4_Review/student-lecture/World/World/Models/ErrorViewModel.cs
using System;

namespace World.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bootcamp/andrewdorscheid-c/Module-3/20_Week4_Review/student-lecture/World/World/Controllers/CityController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using World.Models;
using WorldLib.DAL;
using WorldLib.Models;

namespace World.Controllers
{
    public class CityController : Controller
    {

        /**** DEPENDENCY INJECTION *****/
        private ICityDAO cityDAO;
        private ICountryDAO countryDAO;

        public CityController(ICityDAO cityDAO, ICountryDAO countryDAO)
        {
            this.cityDAO = cityDAO;
            this.countryDAO = countryDAO;
        }

        public IActionResult Index()
        {
            IList<City> cities = cityDAO.GetCities();
            return View(cities);
        }

        public IActionResult Search(CitySearchVM vm)
        {
            // NOTE we are setting a Message if there is no search criteria
            if (vm.CountryCode == null && vm.District == null)
            {
                ViewData["Message"] = "Enter search criteria";
                vm.Cities = new List<City>();
            }
            else
            {
                vm.Cities = cityDAO.GetCities(vm.CountryCode, vm.District);
            }

            // Populate the country list on the view model
            // Call GetCountries() on the countryDAO.
            IList<Country> countries = countryDAO.GetCountries();
            vm.CountryList = new SelectList(countries, "Code", "Name");

            return View(vm);
        }

        // Implement the PRG pattern to ADD a city
        // Add (GET) action to show the form
        [HttpGet]
        public IActionResult Add()
        {
            City city = new City();
            return View(city);
        }

        // Create an Add (POST) method to get the form data and call the dao to add a city
        [HttpPost]
        // Add (GET) action to show the form
        public IActionResult Add(City city)
        {
            // Check model state before updating. If there are errors, return the form to the user.
            if (!ModelState.IsValid)
            {
                return View(city);
            }

            int newCityId = cityDAO.AddCity(city);

            // Add a confirmation message to the user and then re-direct to the search page
            TempData["Message"] = $"City '{city.Name}' was added with id {newCityId}";

            // Redirect to the search page
            CitySearchVM vm = new CitySearchVM()
            {
                CountryCode = city.CountryCode,
                District = city.District
            };
            return RedirectToAction("Search", vm);
        }

        // ConfirmAdd (GET) method to read the added city and call the view
        [HttpGet]
        public IActionResult ConfirmAdd(int id)
        {
            City city = cityDAO.GetCityById(id);
            return View(city);
        }

        // Detail (GET) method to handle the request and show the form
        [HttpGet]
        public IActionResult Detail(int id)
        {
            City city = cityDAO.GetCityById(id);
            if (city == null)
            {
                return NotFound();
            }
            return View(city);
        }


        // Implement the PRG pattern to DELETE a city
        // Delete (GET) method to handle the request and show the form and ask the user to confirm
        [HttpGet]
        public IActionResult Delete(int id)
        {
            City city = cityDAO.GetCityById(id);
            if (city == null)
            {
                return NotFound();
            }
            return View(city);
        }

        // Delete (POST) method to call the dao to delete a city
        [HttpPost]
        public IActionResult Delete(City city)
        {
            cityDAO.DeleteCity(city.CityId);
            return RedirectToAction("ConfirmDelete");
        }

        // ConfirmDelete (GET) method call the view to confirm
        [HttpGet]
        public IActionResult ConfirmDelete()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            // Find the city to update
            City city = cityDAO.GetCityById(id);
            if (city == null)
            {
                return NotFound();
            }

            // Show the form
            return View(city);
        }

        public IActionResult Update(City city)
        {
            // Check model state before updating. If there are errors, return the form to the user.
            if (!ModelState.IsValid)
            {
                return View(city);
            }

            cityDAO.UpdateCity(city);

            // Add a confirmation message to the user and then re-direct to the search page
            TempData["Message"] = $"City '{city.Name}' was updated";

            // Redirect to the Update (GET) page, to re-display the city
            return RedirectToAction("Update", new { id = city.CityId });
        }
    }
}

Bootcamp/andrewdorscheid-c/Module-3/20_Week4_Review/student-lecture/World/World/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using World.Models;

namespace World.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bootcamp/andrewdorscheid-c/Module-3/20_Week4_Review/student-lecture/World/World/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">Welcome to the World</h1>
        <p>(...as it was when Yugoslavia was still a country)</p>
    </div>

Bootcamp/andrewdorscheid-c/Module-3/20_Week4_Review/student-lecture/World/World/Views/Shared/_CityAddUpdate.cshtml
@model City
<div asp-validation-summary="All" class="error validationSummary"></div>

<form asp-controller="City" asp-action="@($"{(Model == null || Model.CityId == 0 ? "Add" : "Update")}")" method="post">
    <input type="hidden" asp-for="CityId" />
    <table class="table table-striped">
        <tbody>
            <tr>
                <td><label asp-for="Name"></label></td>
                <td><input asp-for="Name" /><span asp-validation-for="Name" class="error"></span></td>
            </tr>
            <tr>
                <td><label asp-for="CountryCode"></label></td>
                <td><input asp-for="CountryCode" /><span asp-validation-for="CountryCode" class="error"></span></td>
            </tr>
            <tr>
                <td><label asp-for="District"></label></td>
                <td><input asp-for="District" /><span asp-validation-for="District" class="error"></span></td>
            </tr>
            <tr>
                <td><label asp-for="Population"></label></td>
                <td><input asp-for="Population" /><span asp-validation-for="Population" class="error"></span></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="Submit" value="@($"{(Model == null || Model.CityId == 0 ? "Add" : "Update")} City")" /></td>
            </tr>
        </tbody>
    </table>
</form>

Bootcamp/andrewdorscheid-c/Module-3/20_Week4_Review/student-lecture/World/World/Views/Shared/_CityList.cshtml
@model IList<City>
<table class="table table-striped">
    <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>District</td>
            <td>Country</td>
            <td class="right-justified">Population</td>
        </tr>
    </thead>
    <tbody>
        @foreach (City city in Model)
        {
            <tr>
                <td>@city.CityId</td>
                <td><a asp-controller="City" asp-action="Detail" asp-route-id="@city.CityId">@city.Name</a></td>
                <td>@city.District</td>
                <td>@city.CountryName</td>
                <td class="right-justified">@($"{city.Population:N0}")</td>
            </tr>
        }
    </tbody>
</table>

Bootcamp/andrewdorscheid-c/Module-3/20_Week4_Review/student-lecture/World/World/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - World</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">World</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">All Cities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Search">City Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Add">Add a City</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @{
            string msg = (string)ViewData["Message"];
            if (String.IsNullOrEmpty(msg))
            {
                // Check TempData
                msg = (string)TempData["Message"];
            }

            if (!String.IsNullOrEmpty(msg))
            {
                <div class="alert alert-success alert-dismissible">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>@msg</strong>
                </div>
            }
        }

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TE
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>